version: '3.7'

services:
  web:
    build: .
    command: python /usr/src/google_sheets_cbr/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/google_sheets_cbr
    ports:
      - 8000:8000
    depends_on:
      - pg_db

  bot:  # Telegram_bot
    build: .
    restart: always
    command: python /usr/src/google_sheets_cbr/main.py

  pg_db:
    container_name: pg_db
    image: postgres:10.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

volumes:
  postgres_data:
