version: '3.7'

services:
#  db:
#    image: postgres:10.1-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: python /usr/src/google_sheets_cbr/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/google_sheets_cbr
    ports:
      - 8000:8000
#    depends_on:
#      - db

volumes:
  postgres_data: