# Generated by Django 4.0.5 on 2022-06-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleSheetsCBR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models_sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_Model', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
