# Generated by Django 4.0.5 on 2022-06-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleSheetsCBR', '0002_models_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorts_Model', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Models_sort',
        ),
    ]
