# Generated by Django 4.0.5 on 2022-06-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleSheetsCBR', '0003_modelsort_delete_models_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsort',
            name='ASC_DESK_Model',
            field=models.CharField(default='возрастанию', max_length=30),
        ),
    ]
