# Generated by Django 4.0.5 on 2022-06-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleSheetsCBR', '0004_modelsort_asc_desk_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Models',
        ),
        migrations.AlterField(
            model_name='modelsort',
            name='sorts_Model',
            field=models.CharField(default='№', max_length=30),
        ),
    ]
